### ISSUE TITLE
node 4 doesn't like "let"

### ISSUE THREAD

**Issue by yoshuawuyts** [shuhei/pelo#5]
Heya,

I was porting this package to be used as `bel`'s server part in https://github.com/shama/bel/pull/74, but CI failed on me:

<img width="952" alt="screen shot 2017-05-19 at 13 00 52" src="https://cloud.githubusercontent.com/assets/2467194/26245215/50384452-3c93-11e7-926b-e6cc4bbfaf90.png">

I'm currently just copying in the code from here into `bel`, but I was I was wondering if we could turn this to slightly less fancy JS so we can depend on this package directly from - thanks heaps!

**Comment by yoshuawuyts** [comment]
Patch https://github.com/shama/bel/pull/74/commits/0797eb1f12e9ff684444542ba492c7c2dc880bb7

**Comment by shuhei** [comment]
Yeah, makes sense. I'll update the code :-)

**Comment by shuhei** [comment]
Noticed that we can just use strict mode. `pelo` needs template literals anyway.

**Comment by shuhei** [comment]
Published 0.0.2.
