### ISSUE TITLE
Clean up whitespace

### ISSUE THREAD

**Issue by yoshuawuyts** [shuhei/pelo#7]
I reckon this should probably be a separate module, but bel `v5.0.1` introduced whitespace cleanup. https://github.com/shama/bel/pull/81. This might slow things down on the server, but in return it yields a smaller bundle, and might be up to 3x as fast on the client to render because both leading and trailing text nodes don't have to be created :tada:

**Comment by yoshuawuyts** [comment]
ping @shuhei thoughts?

**Comment by shuhei** [comment]
@yoshuawuyts Sorry, I'm in vacation without a laptop. Will be back in this weekend.

3x fast on client sounds cool! It would be great if it doesn't slow down the server rendering otherwise this library will lose its point. The whitespace cleaning seems to be feasible with O(N), but we need to measure it.

**Comment by yoshuawuyts** [comment]
Cool! - happy holidays :D

Yeah, I think so too - think if the server regresses too much we can find
ways to buffer static results. Let's hang out when you're back;
I'm back in Berlin again. Woot! :D

**Comment by tgfjt** [comment]
Hi there!

https://gist.github.com/tgfjt/34b6b047e5702278de8fa5d509d3ac88
couldn't handle `pre`, `code` tags well so that I use `html-minifier`.
but this seems to be much slower.:/

It's ok to build static html files.
I'm not sure that could it be that good for server side rendering?

**Comment by yoshuawuyts** [comment]
Maybe we should make it a transform instead; ghmmm
https://github.com/stackhtml/documentify

Got the impression @shuhei isn't too comfortable with the idea of minifying
out of the box either. Making this a transform that we can run after would
be a good compromise I think. I can invite you to the org and documentify
repo if you like :D

**Comment by tgfjt** [comment]
@yoshuawuyts 
Interesting, I'd like to.:) No problem?

**Comment by shuhei** [comment]
Sounds good to create a separate module. Then it's gonna be available to more people 😄

**Comment by yoshuawuyts** [comment]
yay! - closing this issue then :D
